export const API_ENDPOINTS = {
  AUTH: {
    SIGNUP: '/auth/signup',
    LOGIN: '/auth/login',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH: '/auth/refresh',
    LOGOUT: '/logout',
  },
  USER: {
    PROFILE: '/user',
    COMPLETE_PROFILE: '/user/complete',
    UPDATE_PROFILE: '/user',
    CHANGE_PASSWORD: '/user/change-password',
    REQUEST_PHONE_CHANGE: '/user/request-phone-change',
    VERIFY_PHONE_CHANGE: '/user/verify-phone-change',
    SWITCH_ROLE: '/user/switch-role',
    SWITCH_ROLE_WITH_DETAILS: '/user/switch-role-with-details',
    APPLICABLE_COUPONS: '/user/applicable-coupons',
    REFERRAL_CODE: '/user/referral-code',
    REFERRAL_STATS: '/user/referral-stats',
  },
  PROVIDER: {
    DETAILS: (id: string) => `/user/providers/${id}` as const,
    DASHBOARD_STATS: '/provider/dashboard/stats',
    NEARBY: '/user/providers/nearby',
  },
  BOOKINGS: {
    BASE: '/bookings',
    LIST: '/bookings',
    MY_BOOKINGS: '/bookings/my-bookings',
    DETAIL: (id: string) => `/bookings/${id}` as const,
    UPDATE: (id: string) => `/bookings/${id}` as const,
    CANCEL: (id: string) => `/bookings/${id}` as const,
    PAYMENT: (bookingId: string) => `/bookings/${bookingId}/payment` as const,
    CONFIRM_PAYMENT: (bookingId: string) => `/bookings/${bookingId}/confirm-payment` as const,
  },
  INVOICES: {
    UPDATE_WITH_ITEMS: (id: string) => `/invoices/${id}/update-with-items` as const,
    DOWNLOAD: (invoiceId: string) => `/invoices/${invoiceId}/download` as const,
  },
  RATINGS: {
    BASE: '/ratings',
    MY_RATINGS: '/ratings/my-ratings',
    PROVIDER_RATINGS: (providerId: string) => `/ratings/provider/${providerId}` as const,
    DETAIL: (id: string) => `/ratings/${id}` as const,
    UPDATE: (id: string) => `/ratings/${id}` as const,
    DELETE: (id: string) => `/ratings/${id}` as const,
  },
  SERVICES: {
    LIST: '/services',
    CREATE: '/services',
    MY_SERVICES: '/services/my-services',
    UPDATE: (id: string) => `/services/${id}` as const,
    DELETE: (id: string) => `/services/${id}` as const,
  },
  CATEGORIES: {
    LIST: '/categories',
    SUB_CATEGORIES: (slug: string) => `/categories/${slug}/sub-categories` as const,
  },
  BLOG: {
    LIST: '/blog',
    FEATURED: '/blog/featured',
    DETAIL: (slug: string) => `/blog/${slug}` as const,
    CATEGORIES: '/blog/categories',
  },
  FAVOURITES: {
    LIST: '/favourites',
    TOGGLE: '/favourites',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/mark-read` as const,
    MARK_ALL_READ: '/notifications/mark-all-read',
    DELETE: (id: string) => `/notifications/${id}` as const,
  },
  FILES: {
    UPLOAD: '/upload',
    DELETE: '/upload',
  },
  DEVICE_TOKENS: {
    REGISTER: '/device-tokens',
    UNREGISTER: '/device-tokens/unregister',
  },
  CONTACT_US: '/contact-us',
  COMMISSIONS: {
    SUMMARY: '/commissions/summary',
    LIST: '/commissions',
  },
  TRANSACTIONS: {
    EARNINGS_SUMMARY: '/transactions/earnings/summary',
    LIST: '/transactions',
  },
  FINANCE_ACCOUNTS: {
    LIST: '/finance-accounts',
    CREATE: '/finance-accounts',
    UPDATE: (id: number) => `/finance-accounts/${id}` as const,
    DELETE: (id: number) => `/finance-accounts/${id}` as const,
  },
} as const;
