export const ROUTES = {
  notifications: '/notifications',
  auth: {
    signin: '/auth/signin',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
    otpVerification: '/auth/otp-verification',
    resetPassword: '/auth/reset-password',
    roleSelection: '/auth/role-selection',
    gettingStarted: '/auth/getting-started',
  },
  guest: {
    home: '/(guest)/(tabs)/home',
    findServices: '/(guest)/(tabs)/find-services',
    beProvider: '/(guest)/(tabs)/be-provider',
    getStarted: '/(guest)/(tabs)/get-started',
    rateApp: '/guest/rate-app',
    aboutSewalo: '/guest/about-sewalo',
    privacyPolicy: '/guest/privacy-policy',
    termsOfService: '/guest/terms-of-service',
    reportProblem: '/guest/report-problem',
    contactSupport: '/guest/contact-support',
  },
  customer: {
    home: '/(customer)/(tabs)/home',
    bookings: '/(customer)/(tabs)/bookings',
    findServices: '/(customer)/(tabs)/find-services',
    favourites: '/(customer)/(tabs)/favourites',
    account: '/(customer)/(tabs)/account',
    editProfile: '/customer/edit-profile',
    changePassword: '/customer/change-password',
    identityVerification: '/customer/identity-verification',
    bookingDetail: (id: string) => `/customer/booking-detail/${id}` as const,
    myReviews: '/customer/my-reviews',
    referFriend: '/customer/refer-friend',
    notificationSettings: '/customer/notification-settings',
    privacySettings: '/customer/privacy-settings',
    helpFaq: '/customer/help-faq',
    contactSupport: '/customer/contact-support',
    termsOfService: '/customer/terms-of-service',
    privacyPolicy: '/customer/privacy-policy',
    rateApp: '/customer/rate-app',
  },
  provider: {
    home: '/(provider)/(tabs)/home',
    services: '/(provider)/(tabs)/services',
    bookings: '/(provider)/(tabs)/bookings',
    earnings: '/(provider)/(tabs)/earnings',
    account: '/(provider)/(tabs)/account',
    serviceEdit: '/provider/service-edit',
    editProfile: '/provider/edit-profile',
    changePassword: '/provider/change-password',
    verificationDocuments: '/provider/verification-documents',
    bookingDetail: (id: string) => `/provider/booking/${id}` as const,
    payoutAccounts: '/provider/payout-accounts',
    notificationSettings: '/provider/notification-settings',
    privacySettings: '/provider/privacy-settings',
    helpFaq: '/provider/help-faq',
    contactSupport: '/provider/contact-support',
    termsOfService: '/provider/terms-of-service',
    privacyPolicy: '/provider/privacy-policy',
    rateApp: '/provider/rate-app',
  },
  bookingConfirmation: '/booking-confirmation',
  providerDetail: (id: string) => `/provider/${id}` as const,
} as const;
