export const ROUTES = {
  notifications: '/notifications',
  auth: {
    signin: '/auth/signin',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
    otpVerification: '/auth/otp-verification',
    resetPassword: '/auth/reset-password',
    roleSelection: '/auth/role-selection',
  },
  guest: {
    home: '/(guest)/home',
    findServices: '/(guest)/find-services',
    beProvider: '/(guest)/be-provider',
    getStarted: '/(guest)/get-started',
  },
  customer: {
    home: '/(customer)/home',
    bookings: '/(customer)/bookings',
    findServices: '/(customer)/find-services',
    favourites: '/(customer)/favourites',
    account: '/(customer)/account',
    editProfile: '/customer/edit-profile',
    changePassword: '/customer/change-password',
    identityVerification: '/customer/identity-verification',
    bookingDetail: (id: string) => `/customer/booking-detail/${id}` as const,
  },
  provider: {
    home: '/(provider)/home',
    services: '/(provider)/services',
    bookings: '/(provider)/bookings',
    earnings: '/(provider)/earnings',
    account: '/(provider)/account',
    serviceEdit: '/provider/service-edit',
    editProfile: '/provider/edit-profile',
    changePassword: '/provider/change-password',
    verificationDocuments: '/provider/verification-documents',
  },
  providerDetail: (id: string) => `/provider/${id}` as const,
} as const;
