export const ROUTES = {
  notifications: '/notifications',
  auth: {
    signin: '/auth/signin',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
    otpVerification: '/auth/otp-verification',
    resetPassword: '/auth/reset-password',
    roleSelection: '/auth/role-selection',
  },
  guest: {
    home: '/(guest)/(tabs)/home',
    findServices: '/(guest)/(tabs)/find-services',
    beProvider: '/(guest)/(tabs)/be-provider',
    getStarted: '/(guest)/(tabs)/get-started',
  },
  customer: {
    home: '/(customer)/(tabs)/home',
    bookings: '/(customer)/(tabs)/bookings',
    findServices: '/(customer)/(tabs)/find-services',
    favourites: '/(customer)/(tabs)/favourites',
    account: '/(customer)/(tabs)/account',
    editProfile: '/customer/edit-profile',
    changePassword: '/customer/change-password',
    identityVerification: '/customer/identity-verification',
    bookingDetail: (id: string) => `/customer/booking-detail/${id}` as const,
  },
  provider: {
    home: '/(provider)/(tabs)/home',
    services: '/(provider)/(tabs)/services',
    bookings: '/(provider)/(tabs)/bookings',
    earnings: '/(provider)/(tabs)/earnings',
    account: '/(provider)/(tabs)/account',
    serviceEdit: '/provider/service-edit',
    editProfile: '/provider/edit-profile',
    changePassword: '/provider/change-password',
    verificationDocuments: '/provider/verification-documents',
    bookingDetail: (id: string) => `/provider/booking/${id}` as const,
  },
  providerDetail: (id: string) => `/provider/${id}` as const,
} as const;
