import { ProviderDetail } from '../types';

export const MOCK_PROVIDERS: Record<string, ProviderDetail> = {
  'pepper-potts': {
    id: 'pepper-potts',
    name: 'Pepper Potts',
    avatarUri: 'https://i.pravatar.cc/300?img=47',
    isVerified: true,
    serviceLabel: 'Design',
    location: 'Kathmandu, Nepal',
    fullLocation: 'Kathmandu Metropolitan City, Bagmati Province',
    rating: '4.2',
    reviewCount: 13,
    startingPrice: 'Rs. 2,000',
    ordersCompleted: '4',
    specialPackagesCount: 1,
    availability: 'Always',
    availabilityLabel: 'Always',
    workingHours: '06:00 am - 06:00 pm',
    phone: '+9779802117361',
    email: 'pepperpotts@gmail.com',
    bio: 'Professional UI/UX and Graphic Designer with 5+ years of experience. Specializing in creating clean, modern, and user-centric designs for websites, mobile applications, and corporate brand identities. I help businesses turn their ideas into visually stunning designs that deliver outstanding results.',
    languages: ['English', 'Nepali', 'Hindi'],
    skills: [
      'UI/UX Design',
      'Logo & Branding',
      'Wireframing',
      'Figma',
      'Adobe Illustrator',
      'Mobile Design',
      'Responsive Web Design',
    ],
    experience: '5+ Years of Professional Experience',
    specialPackage: {
      title: 'Web Design & Branding',
      description:
        'Get a complete branding package and modern website layout tailored specifically for your business growth.',
      inclusions: [
        'Company Branding',
        'Website and application design',
        '3 Revisions included',
        'Figma source files delivered',
      ],
      price: 'Rs. 5,000',
      durationLabel: '10 Days',
    },
    individualServices: [
      {
        id: 'service-1',
        title: 'Logo Design',
        category: 'Design Services',
        price: 'Rs. 5,000',
        durationLabel: '1 Day',
      },
      {
        id: 'service-2',
        title: 'Website Design',
        category: 'Design Services',
        price: 'Rs. 15,000',
        durationLabel: '3 Days',
      },
      {
        id: 'service-3',
        title: 'Mobile App UI/UX',
        category: 'Design Services',
        price: 'Rs. 25,000',
        durationLabel: '5 Days',
      },
    ],
    portfolio: [
      {
        id: 'port-1',
        uri: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=500&auto=format&fit=crop&q=60',
        title: 'E-Commerce Website Redesign',
      },
      {
        id: 'port-2',
        uri: 'https://images.unsplash.com/photo-1541462608141-2ff586485028?w=500&auto=format&fit=crop&q=60',
        title: 'Fintech Mobile Application',
      },
      {
        id: 'port-3',
        uri: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=60',
        title: 'Sewalo Branding Guidelines',
      },
      {
        id: 'port-4',
        uri: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&auto=format&fit=crop&q=60',
        title: 'SaaS Dashboard Analytics',
      },
      {
        id: 'port-5',
        uri: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=500&auto=format&fit=crop&q=60',
        title: 'Real Estate App UI Concept',
      },
      {
        id: 'port-6',
        uri: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=500&auto=format&fit=crop&q=60',
        title: 'Agency Website & Visual Assets',
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        customerName: 'Aayush Shrestha',
        customerAvatar: 'https://i.pravatar.cc/100?img=11',
        rating: 5,
        date: '24 May 2026',
        comment:
          'Pepper Potts is exceptional! She redesigned our company website and the feedback we have got from our users has been incredibly positive. Highly recommended for UI/UX.',
        reply: 'Thank you Aayush! It was great working with your team.',
      },
      {
        id: 'rev-2',
        customerName: 'Sanjana Rai',
        customerAvatar: 'https://i.pravatar.cc/100?img=5',
        rating: 4,
        date: '10 May 2026',
        comment:
          'Very professional and delivers high quality logo drafts. There was a minor delay due to design review iterations, but the final asset was perfect!',
      },
      {
        id: 'rev-3',
        customerName: 'Praveen Karki',
        customerAvatar: 'https://i.pravatar.cc/100?img=15',
        rating: 5,
        date: '02 Apr 2026',
        comment:
          'Quick response time, very communicative, and amazing layout work. Understood exactly what we wanted for our brand guides.',
      },
    ],
  },
  'amina-shrestha': {
    id: 'amina-shrestha',
    name: 'Amina Shrestha',
    avatarUri: 'https://i.pravatar.cc/300?img=32',
    isVerified: true,
    serviceLabel: 'Cleaning',
    location: 'Boudha, Kathmandu',
    fullLocation: 'Boudha Ward-6, Kathmandu, Bagmati Province',
    rating: '4.8',
    reviewCount: 0,
    startingPrice: 'Rs. 1,800',
    ordersCompleted: '18',
    specialPackagesCount: 0,
    availability: 'Always',
    availabilityLabel: 'Always',
    workingHours: '08:00 am - 05:00 pm',
    phone: '+9779876543210',
    email: 'amina.shrestha@gmail.com',
    bio: 'Dedicated home cleaning professional. I provide high-standard vacuuming, dusting, mopping, kitchen sanitation, and deep clean service options. Standard and eco-friendly cleaning supplies can be supplied on request.',
    languages: ['Nepali', 'English'],
    skills: ['Deep Cleaning', 'Sanitization', 'Kitchen Organizing', 'Eco-friendly Supplies', 'Laundry & Ironing'],
    experience: '3+ Years of Professional Cleaning Service',
    specialPackage: null,
    individualServices: [
      {
        id: 'service-1',
        title: 'Room Cleaning',
        category: 'Cleaning Services',
        price: 'Rs. 1,800',
        durationLabel: '1 Day',
      },
      {
        id: 'service-2',
        title: 'Full House Deep Cleaning',
        category: 'Cleaning Services',
        price: 'Rs. 8,000',
        durationLabel: '2 Days',
      },
    ],
    portfolio: [], // Empty Portfolio for testing fallback
    reviews: [], // Empty Reviews for testing fallback
  },
};
