import type { NotificationItem } from '@/types';

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'booking',
    title: 'Booking Confirmed',
    message: 'Your booking with Pepper Potts for Design service has been confirmed.',
    timestamp: '2 min ago',
    read: false,
    actionable: true,
    relatedId: 'booking-1',
  },
  {
    id: 'notif-2',
    type: 'payment',
    title: 'Payment Received',
    message: 'Payment of Rs. 2,300 for Design service has been successfully processed.',
    timestamp: '15 min ago',
    read: false,
  },
  {
    id: 'notif-3',
    type: 'review',
    title: 'New Review',
    message: 'Pepper Potts left you a 5-star review. Tap to view details.',
    timestamp: '1 hour ago',
    read: true,
    actionable: true,
    relatedId: 'review-1',
  },
  {
    id: 'notif-4',
    type: 'system',
    title: 'Profile Updated',
    message: 'Your profile information has been updated successfully.',
    timestamp: '3 hours ago',
    read: true,
  },
  {
    id: 'notif-5',
    type: 'booking',
    title: 'Booking Reminder',
    message: 'Reminder: You have a cleaning service scheduled tomorrow at 10:00 AM.',
    timestamp: '5 hours ago',
    read: false,
    actionable: true,
    relatedId: 'booking-2',
  },
  {
    id: 'notif-6',
    type: 'promo',
    title: 'Special Offer',
    message: 'Get 20% off on your next plumbing service. Offer valid until end of month.',
    timestamp: '1 day ago',
    read: true,
    actionable: true,
  },
  {
    id: 'notif-7',
    type: 'payment',
    title: 'Payment Failed',
    message:
      'Your payment of Rs. 1,800 for Plumbing service could not be processed. Please update your payment method.',
    timestamp: '2 days ago',
    read: false,
    actionable: true,
  },
  {
    id: 'notif-8',
    type: 'booking',
    title: 'Booking Cancelled',
    message: 'Your booking with Sita Rana for Beauty service has been cancelled.',
    timestamp: '3 days ago',
    read: true,
    relatedId: 'booking-4',
  },
  {
    id: 'notif-9',
    type: 'system',
    title: 'Welcome to Sewalo',
    message: 'Welcome! Start exploring services and book your first professional today.',
    timestamp: '1 week ago',
    read: true,
  },
  {
    id: 'notif-10',
    type: 'review',
    title: 'Rating Request',
    message: 'How was your experience with Sam Williams? Leave a review to help the community.',
    timestamp: '1 week ago',
    read: false,
    actionable: true,
    relatedId: 'booking-2',
  },
];
